export function getDom() {
  return {
    app: document.getElementById('app'),
    container: document.getElementById('gameContainer'),
    menuButton: document.getElementById('menuButton'),
    menuPanel: document.getElementById('menuPanel'),
    menuBackdrop: document.getElementById('menuBackdrop'),
    levelFileInput: document.getElementById('levelFileInput'),
    backgroundFileInput: document.getElementById('backgroundFileInput'),
    importButton: document.getElementById('importButton'),
    backgroundButton: document.getElementById('backgroundButton'),
    reloadButton: document.getElementById('reloadButton'),
    starsEl: document.getElementById('starsValue'),
    livesEl: document.getElementById('livesValue'),
    keysEl: document.getElementById('keysValue'),
    bootsEl: document.getElementById('bootsValue'),
    bootsCard: document.getElementById('bootsCard'),
    messageEl: document.getElementById('message'),
    winBackdrop: document.getElementById('winBackdrop'),
    winModal: document.getElementById('winModal'),
    winStars: document.getElementById('winStars'),
    restartButton: document.getElementById('restartButton'),
    newLevelButton: document.getElementById('newLevelButton'),
    deathBackdrop: document.getElementById('deathBackdrop'),
    deathModal: document.getElementById('deathModal'),
    deathLives: document.getElementById('deathLives'),
    deathRestartButton: document.getElementById('deathRestartButton'),
    deathNewLevelButton: document.getElementById('deathNewLevelButton'),
  };
}
