export const gameConfig = {
  title: 'Stardraw',
  tileSize: 0.06,
  world: {
    groundDepth: 0.12,
    emptyColor: '#FFFFFF',
    backgroundTop: '#9ed0ff',
    backgroundBottom: '#eef8ff',
    fitPadding: 1.08,
    cameraFollowTightnessX: 4.2,
    cameraFollowTightnessY: 3.6,
    fuzzOpacity: 0.7,
    fuzzBlur: 0.1,
    terrainOpacityWithBackground: 0.28,
  },
  player: {
    width: 2,
    height: 4,
    moveSpeed: 10,
    accelerationGround: 42,
    accelerationAir: 18,
    frictionGround: 28,
    frictionAir: 4,
    gravity: 32,
    maxFallSpeed: 22,
    jumpVelocity: 16.8,
    jumpCutMultiplier: 0.5,
    coyoteTime: 0.08,
    jumpBufferTime: 0.12,
    stepHeight: 0.42,
    maxLives: 3,
    jumpBootsMultiplier: 2,
    startColor: '#3F48CC',
    color: '#4d63ff',
  },
  goal: {
    color: '#22B14C',
    glowColor: '#78ff9c',
    bobHeight: 0.18,
    bobSpeed: 2.5,
    radius: 1.2,
    coreRadius: 0.62,
  },
  star: {
    color: '#FFF200',
    glowColor: '#ffe766',
    bobHeight: 0.18,
    bobSpeed: 4,
    spinSpeed: 1.8,
    radius: 0.9,
    innerRadius: 0.42,
    depth: 0.22,
  },
  key: {
    color: '#808080',
    glowColor: '#d4d4d4',
    bobHeight: 0.12,
    bobSpeed: 3.6,
    radius: 0.72,
  },
  lava: {
    color: '#880015',
  },
  door: {
    color: '#B97A57',
    topColor: '#b97a57',
    sideColor: '#8d5f43',
  },
  heart: {
    color: '#FF0000',
    glowColor: '#ff7a7a',
    bobHeight: 0.12,
    bobSpeed: 3.4,
    radius: 0.72,
  },
  jumpBoots: {
    color: '#99D9EA',
    glowColor: '#d6f5ff',
    bobHeight: 0.12,
    bobSpeed: 3,
    radius: 0.78,
  },
  tiles: {
    solidColor: '#000000',
    topColor: '#2a2d34',
    sideColor: '#16181d',
  },
  ui: {
    winMessageDurationMs: 2600,
  },
};

export const semanticColorRoles = {
  empty: gameConfig.world.emptyColor,
  solid: gameConfig.tiles.solidColor,
  playerStart: gameConfig.player.startColor,
  goal: gameConfig.goal.color,
  star: gameConfig.star.color,
  key: gameConfig.key.color,
  lava: gameConfig.lava.color,
  door: gameConfig.door.color,
  heart: gameConfig.heart.color,
  jumpBoots: gameConfig.jumpBoots.color,
};
