export const gameConfig = {
  title: 'Stardraw',
  tileSize: 1,
  pixelsPerUnit: 16,
  world: {
    groundDepth: 0.9,
    emptyColor: '#FFFFFF',
    backgroundTop: '#dfefff',
    backgroundBottom: '#f6fbff',
  },
  player: {
    width: 0.68,
    height: 1.2,
    moveSpeed: 8.8,
    accelerationGround: 90,
    accelerationAir: 34,
    frictionGround: 60,
    frictionAir: 8,
    gravity: 30,
    maxFallSpeed: 22,
    jumpVelocity: 11.5,
    jumpCutMultiplier: 0.5,
    coyoteTime: 0.08,
    jumpBufferTime: 0.12,
    startColor: '#3F48CC',
    color: '#4d63ff',
  },
  goal: {
    color: '#22B14C',
    glowColor: '#78ff9c',
    bobHeight: 0.18,
    bobSpeed: 2.5,
  },
  star: {
    color: '#FFF200',
    glowColor: '#ffe766',
    bobHeight: 0.14,
    bobSpeed: 4,
    spinSpeed: 1.8,
  },
  tiles: {
    solidColor: '#000000',
    topColor: '#222222',
    sideColor: '#111111',
  },
  ui: {
    winMessageDurationMs: 2600,
  },
};
